sygmaprotocol/sygma-sdk

packages/sdk/package.json
=> fix version number

.github/.dependabot.yaml, .github/workflows/pr.yaml, .github/workflows/release.yml, package.json
=> Package publishing

.github/workflows/release.yml
=> chore: Release trigger fix

.github/workflows/release.yml
=> chore: fix release workflow definition

.github/workflows/release.yml
=> chore: fix release job definition

.github/workflows/pr.yaml, .github/workflows/release.yml, CHANGELOG.md
Reverts sygmaprotocol/sygma-sdk#15
=> revert: "chore(main): release 1.0.0"

.github/workflows/release.yml, CHANGELOG.md, package.json
Reverts sygmaprotocol/sygma-sdk#37
=> revert: "chore(main): release 1.0.1"

.github/workflows/release.yml, CHANGELOG.md, package.json, packages/sdk/package.json
Reverts sygmaprotocol/sygma-sdk#61
=> revert: "chore(main): release 1.0.1""

.github/workflows/release.yml, package.json, packages/sdk/package.json, release-please-config.json
- Move package publishing to NPM package registry
- Fix release-please configuration
=> chore: publish package on npm registry

README.md, package.json, packages/sdk/package.json
- Update `package.json` of SDK
- Remove lerna related instructions from README file
=> chore: update sdk package.json file

.npmrc, README.md, examples/node-example/package.json, examples/react-example/package.json, packages/sdk/package.json, packages/sdk/src/Sygma.ts, packages/sdk/src/chains/EVM/ERC20Bridge/ERC20Bridge.ts, packages/sdk/src/fee/__test__/basicFee.test.ts, packages/sdk/src/fee/__test__/feeOracle.test.ts, packages/sdk/src/fee/basicFee.ts, packages/sdk/src/fee/feeOracle.ts, packages/sdk/src/types/types.ts, packages/sdk/src/utils/index.ts, yarn.lock
- Change SDK dependencies and example packages to `@buildwithsygma` org.
- Refactor imports according to naming changes.
- Add install instructions to the README file.
=> chore: code cleanup for v1.0.0 release

README.md, examples/node-example/local-setup-example/index.ts, packages/sdk/README.md
=> fix: updated readme

README.md
Updated root readme with instructions and providing contract addresses from our local setup
Update code sample and instructions
Closes: #95
=> chore: update root readme

examples/generic-colors/src/App.tsx
Resets any of the checkbox checked state after deposit
=> fix: reset checkbox checked state after deposit

.github/workflows/release.yml
=> chore: CI fix for monorepo

.github/workflows/release.yml
Reverts sygmaprotocol/sygma-sdk#105
=> revert: "chore: CI fix for monorepo"

.github/workflows/release.yml, .release-please-manifest.json
=> fix: CI release please

.github/workflows/release.yml
=> fix: change github to npm token and publish command

.release-please-manifest.json
=> fix: changed manifest

.release-please-manifest.json
Reverts sygmaprotocol/sygma-sdk#112
=> revert: "fix: changed manifest"

examples/node-example/README.md
=> fix: readme node

packages/sdk/README.md
=> fix: updated readme in sdk

packages/sdk/README.md
=> fix: add getApproved to the readme

packages/sdk/src/Sygma.ts
=> fix: destination network selection 

packages/sdk/src/fee/__test__/basicFee.test.ts, packages/sdk/src/fee/basicFee.ts
=> fix: fix imports

packages/sdk/src/Sygma.ts, packages/sdk/src/chains/EVM/EvmBridge/EvmBridge.ts, packages/sdk/src/types/types.ts
=> feat: Add blocks confirmation amount param to config

packages/sdk/src/Sygma.ts, packages/sdk/src/chains/EVM/EvmBridge/EvmBridge.ts, packages/sdk/src/connectors/Connectors.ts, packages/sdk/src/fee/basicFee.ts, packages/sdk/src/fee/feeOracle.ts, packages/sdk/src/types/types.ts, packages/sdk/src/utils/helpers.ts, packages/sdk/src/utils/index.ts
Add TS Docs annotations over all the methods
Closes: #96
=> chore: adding ts docs

packages/sdk/src/connectors/Connectors.ts, packages/sdk/src/utils/helpers.ts
=> fix: linter issues

examples/generic-colors/src/App.tsx, examples/generic-colors/src/utils/index.ts, examples/generic-node-example/src/abis/decodeColor.ts, examples/generic-node-example/src/depositGeneric.ts, packages/sdk/src/fee/feeOracle.ts, packages/sdk/src/utils/index.ts
refactor deprecated `substr` with `substring`
Closes: #156
=> fix: usage of deprecated `substr`

packages/sdk/src/fee/feeOracle.ts
Fix url to query fee oracle service, passing `msgGasLimit` as query param
Closes: #160
=> fix: Fix url to query oracle service

packages/sdk/src/Sygma.ts, packages/sdk/src/fee/__test__/basicFee.test.ts, packages/sdk/src/fee/__test__/feeOracle.test.ts, packages/sdk/src/fee/basicFee.ts, packages/sdk/src/fee/feeOracle.ts, packages/sdk/src/utils/helpers.ts
=> fix: fix amount in createOracleFeeData

examples/node-example/tsconfig.json, packages/sdk/config/config_evm-evm.json, packages/sdk/integration/contracts/ERC20Custom.json, packages/sdk/tsconfig.build.json, packages/sdk/tsconfig.json, release-please-config.json
some files are been mess or had different indents, this PR is fixed and standardized to 2 spaces (most of json had that already) across the project
=> chore: reformat json's

.github/workflows/release.yml
=> chore: Update CI to yarn v3

packages/sdk/.eslintrc.cjs, packages/sdk/package.json, packages/sdk/src/Sygma.ts, packages/sdk/src/fee/__test__/feeHandler.test.ts, packages/sdk/src/fee/feeHandler.ts, packages/sdk/src/fee/index.ts, packages/sdk/src/types/types.ts
=> feat: Methods to set fee settings and general usage with shared config

examples/evm-to-substrate-react-example/README.md, examples/substrate-to-evm-react-example/README.md
=> chore: Add README to substrate example

.gitignore, packages/sdk/jest.config.cjs, packages/sdk/package.json, packages/sdk/src/Config.ts, packages/sdk/src/config.ts, packages/sdk/src/constants.ts, packages/sdk/src/index.ts, packages/sdk/src/types/config.ts, packages/sdk/test/config/config.test.ts, packages/sdk/test/constants.ts, yarn.lock
* adds `Config` class for fetching configuration file
* adds typings for the corresponding `Config` class
Closes: #228 
- unit tests
=> feat: add Config class and types

packages/sdk/src/chains/EVM/__test__/helpers.test.ts, packages/sdk/src/chains/EVM/helpers.ts
Update permissionless generic deposit data creation.
Closes: #245 
Closes: #247
=> fix: update permissionless generic deposit data

.github/workflows/release.yml
Remove broken pre-release github action.
=> fix: remove pre-release action

packages/sdk/LICENSE
Add license content to the SDK package directly.
=> fix: add license to the sdk package

packages/sdk/src/chains/Substrate/__test__/deposit.test.ts, packages/sdk/src/chains/Substrate/assetTransfer.ts, packages/sdk/src/chains/Substrate/utils/depositFns.ts
Closes: #269 
Tested for successful execution of Substrate -> EVM transfer
=> fix: update createDestinationMultiLocation to use Xcm V3 Multilocation

examples/local-fungible-transfer/src/transfer.ts
Didn't push last commit that was resolving few issues with local example :see_no_evil:
=> fix: local example

examples/evm-to-evm-fungible-transfer/package.json, examples/evm-to-substrate-fungible-transfer/package.json, examples/local-fungible-transfer/package.json, examples/substrate-to-evm-fungible-transfer/package.json, yarn.lock
Updated all examples to use the latest version of the SDK.
N/A
All examples run as required.
=> fix: Update examples to use latest sdk

README.md
last one... did not update ## Support section's Discord badge
=> chore: update Support section discord badge

.github/workflows/docs.yml
Change target branch for typedocs genearing action
=> fix: change target branch for typedocs

examples/evm-to-evm-fungible-transfer/package.json, examples/evm-to-evm-generic-mesage-passing/package.json, examples/evm-to-substrate-fungible-transfer/package.json, examples/local-fungible-transfer/package.json, examples/substrate-to-evm-fungible-transfer/package.json, yarn.lock
Updated workspace package references to resolve release-please CI issue
CI fails on release-please PRs https://github.com/sygmaprotocol/sygma-sdk/actions/runs/6261842992/job/17002751292#step:5:87
Will be tested in CI
=> chore: release please ci

examples/substrate-to-evm-fungible-transfer/README.md, examples/substrate-to-evm-fungible-transfer/src/transfer.ts
Small fix on example and readme
=> chore: small fixes to substrate to evm example

packages/sdk/src/chains/EVM/assetTransfer.ts, packages/sdk/src/chains/EVM/utils/depositFns.ts, packages/sdk/test/chains/EVM/assetTransfer.test.ts
fix erc20Approvals
remove dynamic fee handler type and use percentage type
=> fix: fix erc20Approvals

packages/sdk/src/chains/EVM/assetTransfer.ts, packages/sdk/src/chains/EVM/utils/depositFns.ts, packages/sdk/test/chains/EVM/assetTransfer.test.ts
Reverts sygmaprotocol/sygma-sdk#311
=> fix: revert fix erc20Approvals

packages/sdk/src/chains/EVM/assetTransfer.ts, packages/sdk/src/chains/EVM/utils/depositFns.ts, packages/sdk/test/chains/EVM/assetTransfer.test.ts
use percentage fee handler instead of dynamic
=> fix: fix approvals

examples/evm-to-substrate-fungible-transfer/src/transfer.ts
the faucet only gives 1 GPHA so updating the tutorial to send 0.5 GPHA instead of 5
=> chore: Update transfer.ts to transfer 0.5 GPHA tokens since the faucet only sends 1 GPHA

examples/evm-to-substrate-fungible-transfer/README.md
=> chore: Update README.md for evm-to-substrate transfer so that users know to which faucet token to retrieve

examples/evm-to-evm-fungible-transfer/src/transfer.ts
Update transfer.ts to transfer 5 tokens instead of 50 so that the tutorial can work once the user claims once
=> chore: Update transfer.ts to transfer 5 tokens instead of 50

packages/sdk/src/chains/BaseAssetTransfer.ts, packages/sdk/src/chains/EVM/utils/getEvmBalances.ts, packages/sdk/src/chains/EVM/utils/index.ts
This PR exposes function to get balance of ERC20 token and introduces small refactor of the file where `getEvmHandlerBalance` was placed
Closes: #323
=> feat: small refactor to get balances on Evm context

packages/sdk/src/chains/EVM/fee/basicFee.ts
- Fixes import for basicFee file that apparently was missed by new linter
=> fix: ethers util import in basicFee

.github/workflows/ci.yaml, packages/sdk/package.json, yarn.lock
=> fix: update sygma contracts dep

packages/sdk/src/chains/BaseAssetTransfer.ts, packages/sdk/src/chains/EVM/assetTransfer.ts, packages/sdk/src/chains/EVM/fee/feeHandler.ts, packages/sdk/src/chains/EVM/genericMessage.ts, packages/sdk/src/chains/Substrate/assetTransfer.ts, packages/sdk/src/chains/Substrate/utils/getFeeHandler.ts, packages/sdk/src/types/types.ts, packages/sdk/src/utils.ts, packages/sdk/test/chains/EVM/assetTransfer.test.ts, packages/sdk/test/chains/Substrate/assetTransfer.test.ts, yarn.lock
As result of my effort to implement #334 directly into SDK, made some small changes that I would leave here:
- util function that checks if the route exists from source chain router
- removed the old dynamic fee code as it is not relevant anymore
- Expanded unit tests
=> fix: remove unused dynamic fees support

packages/sdk/src/utils.ts
Closes #341 
Fix the bug with data from the new endpoint.
Figure out that while making this PR I did some over-engineering with overloads...
=> fix: getTransferStatusData

packages/sdk/src/utils.ts, packages/sdk/test/utils.test.ts
Fix bug on util function getRoutes when fetching all routes
=> fix: get all routes

packages/sdk/src/chains/Substrate/utils/getAssetBalance.ts, packages/sdk/src/chains/Substrate/utils/getSubstrateHandlerBalance.ts, packages/sdk/src/config/localConfig.ts, packages/sdk/src/types/types.ts
- This PR renames attribute to match shared-config
=> fix: change in config invalid assetId property name into assetID as defined by remote config

packages/sdk/src/chains/EVM/fee/percentageFee.ts, packages/sdk/src/chains/EVM/types/index.ts
=> feat: add bounds to percentage fee response

packages/sdk/src/chains/EVM/fee/percentageFee.ts, packages/sdk/src/chains/EVM/types/index.ts
=> feat: add fee percentage to percentage fee details

README.md, examples/evm-to-evm-fungible-transfer/README.md, package.json
Updated readme to reflect newer version of the SDK
=> chore: Update v3 documentation

packages/btc/src/base-transfer.ts, packages/btc/src/index.ts, packages/core/src/types.ts
=> feat: btc interfaces definition

packages/evm/src/fungible.ts
=> fix: Fixed maximum stack call error

packages/sdk/README.md
=> chore: update readme

packages/sdk/README.md
fix grammar
fix grammar in readme
=> feat: fix grammar

packages/sdk/.npmignore
Remove config folder from npmignore
=> fix: release

packages/evm/src/fungible.ts, packages/evm/src/types.ts, packages/evm/src/utils/__test__/depositFns.test.ts, packages/evm/src/utils/depositFns.ts
=> fix: Fee issue on cronos causes transaction to fail

examples/evm-to-evm-generic-message-transfer/src/transfer.ts, packages/evm/src/baseTransfer.ts, packages/evm/src/fungible.ts
=> fix: fixed faulty branch merge that breaks GMP

.github/workflows/release-core.yml
Workflow file to release `@buildwithsygma/core` package.
#416 
Closes: #416 (partially)
Not tested
=> chore: Added `release-core.yml`

.github/workflows/release-evm.yml
Workflow file to release `@buildwithsygma/evm` package.
#416 
Closes: #416 (partially)
Not tested
=> chore: Added `release-evm.yml`

.github/workflows/release-substrate.yml
Workflow file to release `@buildwithsygma/substrate` package.
#416 
Closes: #416 (partially)
Not tested
=> chore: Added `release-substrate.yml`

.github/workflows/docs.yml
=> fix: Fix docs workflow failure

.github/workflows/docs.yml
=> chore: build docs

.github/workflows/release-core.yml, .github/workflows/release-evm.yml, .github/workflows/release-substrate.yml, packages/core/package.json, packages/evm/package.json, packages/substrate/package.json
=> chore: trigger releases for core, evm and substrate

.github/workflows/release-core.yml, .github/workflows/release-evm.yml, .github/workflows/release-substrate.yml, .release-please-manifest.json
=> fix: release please

packages/core/README.md
=> chore: Trigger release

packages/evm/README.md, packages/evm/package.json, yarn.lock
=> fix: EVM dependency

.github/workflows/release-substrate.yml, packages/substrate/README.md, packages/substrate/package.json, yarn.lock
=> fix: substrate command update

packages/evm/src/types.ts
=> chore: update comments to create a stable evm release

examples/evm-to-evm-fungible-transfer/src/transfer.ts, examples/substrate-to-evm-fungible-transfer/package.json, examples/substrate-to-evm-fungible-transfer/src/transfer.ts, packages/core/src/index.ts, packages/core/tsconfig.json, packages/evm/src/__test__/fungible.test.ts, packages/evm/src/evmTransfer.ts, packages/evm/src/fee/index.ts, packages/evm/src/fee/types.ts, packages/evm/src/fungible.ts, packages/evm/src/utils/approveAndCheckFns.ts, packages/evm/src/utils/index.ts, packages/substrate/package.json, packages/substrate/src/__test__/fungible.test.ts, packages/substrate/src/__test__/utils/getAssetBalance.test.ts, packages/substrate/src/__test__/utils/getNativeTokenBalance.test.ts, packages/substrate/src/fungible.ts, packages/substrate/src/index.ts, packages/substrate/src/utils/getAssetBalance.ts, packages/substrate/src/utils/getNativeTokenBalance.ts, packages/substrate/src/utils/index.ts, packages/utils/src/__test__/liquidity.test.ts, packages/utils/src/environment.d.ts, packages/utils/src/liquidity.ts, packages/utils/src/substrate/balances.ts, yarn.lock
=> fix!: throw an error when the source account has low balance

examples/evm-to-evm-fungible-transfer/src/transfer.ts, examples/substrate-to-evm-fungible-transfer/package.json, examples/substrate-to-evm-fungible-transfer/src/transfer.ts, packages/core/tsconfig.json, packages/evm/src/__test__/fungible.test.ts, packages/evm/src/evmTransfer.ts, packages/evm/src/fee/index.ts, packages/evm/src/fee/types.ts, packages/evm/src/fungible.ts, packages/evm/src/utils/approveAndCheckFns.ts, packages/evm/src/utils/index.ts, packages/substrate/package.json, packages/substrate/src/__test__/fungible.test.ts, packages/substrate/src/__test__/utils/getAssetBalance.test.ts, packages/substrate/src/__test__/utils/getNativeTokenBalance.test.ts, packages/substrate/src/fungible.ts, packages/substrate/src/utils/getAssetBalance.ts, packages/substrate/src/utils/getNativeTokenBalance.ts, packages/substrate/src/utils/index.ts, packages/utils/src/__test__/liquidity.test.ts, packages/utils/src/environment.d.ts, packages/utils/src/liquidity.ts, packages/utils/src/substrate/balances.ts, yarn.lock
=> fix: Add low balance validation 

packages/evm/src/evmTransfer.ts
=> fix: Add missing `getDepositData`

packages/core/src/utils.ts
=> fix: edge incompatibility 

packages/evm/src/__test__/fungible.test.ts, packages/evm/src/evmAssetTransfer.ts, packages/evm/src/fungibleAssetTransfer.ts, packages/evm/src/nonFungibleAssetTransfer.ts, packages/evm/src/types.ts, packages/evm/src/utils/approveAndCheckFns.ts, packages/evm/src/utils/transaction.ts
This PR adds the optional ethereum transaction parameters to Sygma fungible transfer classes.
[X] Unit test detecting `gasPrice` and `gasLimit`
=> fix: added ethereum transaction overrides

packages/evm/src/utils/approveAndCheckFns.ts
Fix approval argument error thrown by ethers
=> fix: approval failure with no transaction overrides
